name: ssac
channels:
  - robostack
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.7.22=hbcca054_0
  - certifi=2023.7.22=pyhd8ed1ab_0
  - contourpy=1.0.5=py310hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.4.9=h6a678d5_0
  - fontconfig=2.14.1=h52c9d5c_1
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.69.1=he621ea3_2
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=58.2=he6710b0_3
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h5eee18b_1
  - kiwisolver=1.4.4=py310h6a678d5_0
  - krb5=1.19.4=h568e23c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libclang=10.0.1=default_hb85057a_2
  - libdeflate=1.17=h5eee18b_0
  - libedit=3.1.20221030=h5eee18b_0
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libllvm10=10.0.1=hbcb73fb_5
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.9=h16c4e8d_3
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.0=h6a678d5_2
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - lz4-c=1.9.4=h6a678d5_0
  - matplotlib=3.7.1=py310h06a4308_0
  - matplotlib-base=3.7.1=py310h1128e8f_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310h7f8727e_0
  - mkl_fft=1.3.1=py310hd6ae3a3_0
  - mkl_random=1.2.2=py310h00e6091_0
  - munkres=1.1.4=py_0
  - ncurses=6.4=h6a678d5_0
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - numpy=1.23.5=py310hd5efca6_0
  - numpy-base=1.23.5=py310h8e6c178_0
  - openssl=1.1.1w=h7f8727e_0
  - packaging=23.0=py310h06a4308_0
  - pcre=8.45=h295c915_0
  - pillow=9.4.0=py310h6a678d5_0
  - pip=23.0.1=py310h06a4308_0
  - ply=3.11=py310h06a4308_0
  - pyparsing=3.0.9=py310h06a4308_0
  - pyqt=5.15.7=py310h6a678d5_1
  - python=3.10.9=h7a1cb2a_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtwebkit=5.212=h4eab89a_4
  - readline=8.2=h5eee18b_0
  - setuptools=65.6.3=py310h06a4308_0
  - sip=6.6.2=py310h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.1=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.2=py310h5eee18b_0
  - tzdata=2022g=h04d1e81_0
  - wheel=0.38.4=py310h06a4308_0
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - addict==2.4.0
      - asttokens==2.2.1
      - attrs==22.2.0
      - backcall==0.2.0
      - click==8.1.3
      - comm==0.1.2
      - configargparse==1.5.3
      - dash==2.9.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - debugpy==1.6.6
      - decorator==5.1.1
      - deprecated==1.2.14
      - dv==1.0.12
      - executing==1.2.0
      - fastjsonschema==2.16.3
      - flask==2.2.3
      - flatbuffers==23.5.26
      - ipykernel==6.21.3
      - ipython==8.11.0
      - ipywidgets==8.0.4
      - itsdangerous==2.1.2
      - jedi==0.18.2
      - jinja2==3.1.2
      - joblib==1.2.0
      - jsonschema==4.17.3
      - jupyter-client==8.0.3
      - jupyter-core==5.3.0
      - jupyterlab-widgets==3.0.5
      - lz4==4.3.2
      - markupsafe==2.1.2
      - matlabengineforpython==9.13
      - matplotlib-inline==0.1.6
      - nbformat==5.7.0
      - nest-asyncio==1.5.6
      - open3d==0.17.0
      - opencv-python==4.8.0.76
      - pandas==1.5.3
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - platformdirs==3.1.1
      - plotly==5.13.1
      - prompt-toolkit==3.0.38
      - psutil==5.9.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pygments==2.14.0
      - pyqt5-sip==12.11.0
      - pyquaternion==0.9.9
      - pyrsistent==0.19.3
      - pytz==2022.7.1
      - pyyaml==6.0
      - pyzmq==25.0.1
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - stack-data==0.6.2
      - tenacity==8.2.2
      - threadpoolctl==3.1.0
      - tqdm==4.65.0
      - traitlets==5.9.0
      - wcwidth==0.2.6
      - werkzeug==2.2.3
      - widgetsnbextension==4.0.5
      - wrapt==1.15.0
      - zstd==1.5.5.1
prefix: /home/wlxing/Libraries/miniconda3/envs/ssac
